In [1]:
import pandas as pd
import os
from pathlib import Path
from pathlib import PurePosixPath



BASE_DIR = Path("../").resolve().parent

result_file_path = BASE_DIR / "resources" / "data" / "stack-overflow-survey" / "results.csv"
result_file_schema = BASE_DIR /  "resources" / "data" / "stack-overflow-survey" / "schema.csv"

BASE_DIR,result_file_path,result_file_schema



pd.set_option('display.max_columns',170)
pd.set_option('display.max_rows',170)
pd.set_option('display.max_colwidth',172)
pd.set_option('display.max_seq_items', None)

df_schema=pd.read_csv(result_file_schema,index_col='qname')
df = pd.read_csv(result_file_path, index_col='ResponseId')

In [88]:
data = {
    "first": ["Ramesh","Rajesh","Mahesh"],
    "last" : ["Govardhan","singh","pablo"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [3]:
# Adding Columns

In [5]:
df['salary'] = ['1000','1000','1200']

In [6]:
df

    first       last  age            email salary
0  Ramesh  Govardhan   23  ramesh@mail.com   1000
1  Rajesh      singh   34  rajesh@mail.com   1000
2  Mahesh      pablo   25  mahesh@mail.com   1200

In [7]:
# adding first and last combined

In [8]:
df['full_name'] = df['first'] + ' ' + df['last']

In [9]:
df

    first       last  age            email salary         full_name
0  Ramesh  Govardhan   23  ramesh@mail.com   1000  Ramesh Govardhan
1  Rajesh      singh   34  rajesh@mail.com   1000      Rajesh singh
2  Mahesh      pablo   25  mahesh@mail.com   1200      Mahesh pablo

In [10]:
# you can also use apply method to create full name

In [24]:
def full_name_a(row):
    return row['first'] + ' ' + row['last']


df['FullName'] = df.apply(full_name_a, axis=1)

In [19]:
df

,first,last,age,email,salary,full_name,FullName
0,Ramesh,Govardhan,23,ramesh@mail.com,1000,Ramesh Govardhan,Ramesh Govardhan
1,Rajesh,singh,34,rajesh@mail.com,1000,Rajesh singh,Rajesh singh
2,Mahesh,pablo,25,mahesh@mail.com,1200,Mahesh pablo,Mahesh pablo

In [20]:
# drop columns

In [25]:
df.drop(columns=['FullName', 'first','last'], inplace=True)

In [26]:
df

   age            email salary         full_name
0   23  ramesh@mail.com   1000  Ramesh Govardhan
1   34  rajesh@mail.com   1000      Rajesh singh
2   25  mahesh@mail.com   1200      Mahesh pablo

In [27]:
# retunf back first and last

In [29]:
df['full_name'].str.split(' ')

0    [Ramesh, Govardhan]
1        [Rajesh, singh]
2        [Mahesh, pablo]
Name: full_name, dtype: object

In [47]:
df['first_name'] = df['full_name'].map(lambda x: x.split(' ')[0])
df['last_name'] = df['full_name'].map(lambda x: x.split(' ')[1])

In [48]:
df

   age            email salary         full_name first_name  last_name
0   23  ramesh@mail.com   1000  Ramesh Govardhan     Ramesh  Govardhan
1   34  rajesh@mail.com   1000      Rajesh singh     Rajesh      singh
2   25  mahesh@mail.com   1200      Mahesh pablo     Mahesh      pablo

In [49]:
# use expand

In [ ]:
df['full_name'].str.split(' ', expand=True)

        0          1
0  Ramesh  Govardhan
1  Rajesh      singh
2  Mahesh      pablo

In [51]:
df[['first','last']] = df['full_name'].str.split(' ', expand=True)

In [52]:
df

,age,email,salary,full_name,first_name,last_name,first,last
0,23,ramesh@mail.com,1000,Ramesh Govardhan,Ramesh,Govardhan,Ramesh,Govardhan
1,34,rajesh@mail.com,1000,Rajesh singh,Rajesh,singh,Rajesh,singh
2,25,mahesh@mail.com,1200,Mahesh pablo,Mahesh,pablo,Mahesh,pablo

In [53]:
# adding row

In [69]:
new_data = [{"first":"Ajay"}]
new_rows_df = pd.DataFrame(new_data)

In [91]:
df = pd.concat([df, new_rows_df], ignore_index=True)
df

    first       last   age            email
0  Ramesh  Govardhan  23.0  ramesh@mail.com
1  Rajesh      singh  34.0  rajesh@mail.com
2  Mahesh      pablo  25.0  mahesh@mail.com
3    Ajay        NaN   NaN              NaN

In [76]:
df

    first       last   age            email
0  Ramesh  Govardhan  23.0  ramesh@mail.com
1  Rajesh      singh  34.0  rajesh@mail.com
2  Mahesh      pablo  25.0  mahesh@mail.com
3    Ajay        NaN   NaN              NaN

In [77]:
df.loc[len(df)] = {"first": "Demser"}

In [78]:
df

    first       last   age            email
0  Ramesh  Govardhan  23.0  ramesh@mail.com
1  Rajesh      singh  34.0  rajesh@mail.com
2  Mahesh      pablo  25.0  mahesh@mail.com
3    Ajay        NaN   NaN              NaN
4  Demser        NaN   NaN              NaN

In [81]:
df.drop(index=4 , inplace=True)

In [92]:
df

    first       last   age            email
0  Ramesh  Govardhan  23.0  ramesh@mail.com
1  Rajesh      singh  34.0  rajesh@mail.com
2  Mahesh      pablo  25.0  mahesh@mail.com
3    Ajay        NaN   NaN              NaN

In [93]:
df.drop(columns=['email'])

    first       last   age
0  Ramesh  Govardhan  23.0
1  Rajesh      singh  34.0
2  Mahesh      pablo  25.0
3    Ajay        NaN   NaN

In [96]:
filt = (df['age'] == None)

df.drop(index = df[filt].index, inplace=True)

In [97]:
df

    first       last   age            email
0  Ramesh  Govardhan  23.0  ramesh@mail.com
1  Rajesh      singh  34.0  rajesh@mail.com
2  Mahesh      pablo  25.0  mahesh@mail.com
3    Ajay        NaN   NaN              NaN