In [70]:
import pandas as pd
import os
from pathlib import Path
from pathlib import PurePosixPath



BASE_DIR = Path("../").resolve().parent

result_file_path = BASE_DIR / "resources" / "data" / "stack-overflow-survey" / "results.csv"
result_file_schema = BASE_DIR /  "resources" / "data" / "stack-overflow-survey" / "schema.csv"

BASE_DIR,result_file_path,result_file_schema



pd.set_option('display.max_columns',170)
pd.set_option('display.max_rows',170)
pd.set_option('display.max_colwidth',172)
pd.set_option('display.max_seq_items', None)

survey_schema=pd.read_csv(result_file_schema,index_col='qname')
survey_df = pd.read_csv(result_file_path, index_col='ResponseId')

In [3]:
import numpy as np

data = {
    "first": ["Ramesh","Rajesh","Mahesh",'Kajoo', np.nan, None, 'NA'],
    "last" : ["Govardhan","singh","pablo",'Singh',np.nan, np.nan, 'Missing'],
    "age": [23,34,22,22,np.nan, None, None],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com",'kajoor@mail.com', None, np.nan, None],
    "language": [['python','scala','golang'],['scala','golang'],['python','scala','golang'],['scala','golang'], np.nan, None, []],
    "salary":[1000,10029,7298,32793,237927,372973,434342]

}

df = pd.DataFrame(data)
df

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793
4     NaN        NaN   NaN              NaN                      NaN  237927
5     NaN        NaN   NaN              NaN                     None  372973
6      NA    Missing   NaN              NaN                       []  434342

In [4]:
df.dropna()

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793

In [5]:
df.dropna(subset=['last','language'],ignore_index=False) #ignore_index if set to True will assign index sequentially after droping the row/column

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793
6      NA    Missing   NaN              NaN                       []  434342

In [6]:
df.dropna(axis='columns')

   salary
0    1000
1   10029
2    7298
3   32793
4  237927
5  372973
6  434342

In [7]:
df.dropna(axis='index')

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793

In [9]:
#by default it's set 

df.dropna(axis='index', how='any')

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793

In [12]:
# if all rows for index is  null
df.dropna(axis='index', how='all')

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793
4     NaN        NaN   NaN              NaN                      NaN  237927
5     NaN        NaN   NaN              NaN                     None  372973
6      NA    Missing   NaN              NaN                       []  434342

In [14]:
df = pd.DataFrame(
    {
        "name": ["Alfred", "Batman", "Catwoman"],
        "toy": [np.nan, "Batmobile", "Bullwhip"],
        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    }
)

df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [16]:
#Drop the rows where at least one element is missing.
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [18]:
# Drop the columns where at least one element is missing.
df.dropna(axis="columns")

       name
0    Alfred
1    Batman
2  Catwoman

In [20]:
# Drop the rows where all elements are missing.
df.dropna(how="all")

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [23]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [22]:
#Keep only the rows with at least 2 non-NA values.
df.dropna(thresh=2)

       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [25]:
#Define in which columns to look for missing values.

df.dropna(subset=["name", "toy"])

       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [27]:
df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [26]:
df.isna()

    name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

# fillna

In [34]:
updated_df = df.fillna('UKNOWN')
updated_df

       name        toy                 born
0    Alfred     UKNOWN               UKNOWN
1    Batman  Batmobile  1940-04-25 00:00:00
2  Catwoman   Bullwhip               UKNOWN

In [38]:
updated_df.fillna('MISSING')

       name        toy                 born
0    Alfred     UKNOWN               UKNOWN
1    Batman  Batmobile  1940-04-25 00:00:00
2  Catwoman   Bullwhip               UKNOWN

In [42]:
df = pd.DataFrame(
    [
        [np.nan, 2, np.nan, 0],
        [3, 4, np.nan, 1],
        [np.nan, np.nan, np.nan, np.nan],
        [np.nan, 3, np.nan, 4],
    ],
    columns=list("ABCD"),
)
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [44]:
df.fillna(0)

     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0

In [46]:
values = {"A": 0, "B": 1, "C": 2, "D": 3}

df.fillna(value=values)

     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  2.0  1.0
2  0.0  1.0  2.0  3.0
3  0.0  3.0  2.0  4.0

In [48]:
#Only replace the first NaN element
df.fillna(value=values, limit=1)

     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  NaN  1.0
2  NaN  1.0  NaN  3.0
3  NaN  3.0  NaN  4.0

In [53]:
list("ABCE")

['A', 'B', 'C', 'E']

In [54]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
#When filling using a DataFrame, replacement
#  happens along the same column names and same indices


df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
df2

     A    B    C    E
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0

In [55]:
df.fillna(df2)

     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  NaN
3  0.0  3.0  0.0  4.0

# data types

In [57]:

data = {
    "first": ["Ramesh","Rajesh","Mahesh",'Kajoo', np.nan, None, 'NA'],
    "last" : ["Govardhan","singh","pablo",'Singh',np.nan, np.nan, 'Missing'],
    "age": [23,34,22,22,np.nan, None, None],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com",'kajoor@mail.com', None, np.nan, None],
    "language": [['python','scala','golang'],['scala','golang'],['python','scala','golang'],['scala','golang'], np.nan, None, []],
    "salary":[1000,10029,7298,32793,237927,372973,434342]

}

df = pd.DataFrame(data)
df

    first       last   age            email                 language  salary
0  Ramesh  Govardhan  23.0  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh  34.0  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo  22.0  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh  22.0  kajoor@mail.com          [scala, golang]   32793
4     NaN        NaN   NaN              NaN                      NaN  237927
5     NaN        NaN   NaN              NaN                     None  372973
6      NA    Missing   NaN              NaN                       []  434342

In [59]:
df.dtypes

first           str
last            str
age         float64
email           str
language     object
salary        int64
dtype: object

In [65]:
#change afe to Integer

df['age'] = df['age'].astype('float')

In [67]:
df.dtypes

first           str
last            str
age         float64
email           str
language     object
salary        int64
dtype: object

In [68]:
df.convert_dtypes()

    first       last   age            email                 language  salary
0  Ramesh  Govardhan    23  ramesh@mail.com  [python, scala, golang]    1000
1  Rajesh      singh    34  rajesh@mail.com          [scala, golang]   10029
2  Mahesh      pablo    22  mahesh@mail.com  [python, scala, golang]    7298
3   Kajoo      Singh    22  kajoor@mail.com          [scala, golang]   32793
4    <NA>       <NA>  <NA>             <NA>                      NaN  237927
5    <NA>       <NA>  <NA>             <NA>                     None  372973
6      NA    Missing  <NA>             <NA>                       []  434342

In [69]:
df.dtypes

first           str
last            str
age         float64
email           str
language     object
salary        int64
dtype: object

# back to survey result

In [82]:
# Assigning NAN value to missing and na , none value while reading

missing_value = ['NA','Missing']
df = pd.read_csv(result_file_path, index_col='ResponseId', na_values=missing_value)

In [77]:
df.columns

Index(['qid', 'question', 'force_resp', 'type', 'selector'], dtype='str')

In [84]:
df['YearsCode'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [85]:
df['YearsCode'] = df['YearsCode'].astype('float')

ValueError: could not convert string to float: 'More than 50 years'

In [89]:
df['YearsCode'].unique()

<StringArray>
[                 nan,                 '20',                 '37',
                  '4',                  '9',                 '10',
                  '7',                  '1',                 '15',
                 '30',                 '31',                  '6',
                 '12',                 '22',                  '5',
                 '36',                 '25',                 '44',
                 '24',                 '18',                  '3',
                  '8', 'More than 50 years',                 '11',
                 '29',                 '40',                 '39',
                  '2',                 '42',                 '34',
                 '19',                 '35',                 '16',
                 '33',                 '13',                 '23',
                 '14',                 '28',                 '17',
                 '21',                 '43',                 '46',
                 '26',                 '32',                 '41',
                 '45',                 '27',                 '38',
                 '50',                 '48',                 '47',
   'Less than 1 year',                 '49']
Length: 53, dtype: str

In [91]:
df['YearsCode'] = df['YearsCode'].replace({'More than 50 years':'50', 'Less than 1 year':'0'})

In [93]:
df['YearsCode'].unique()

<StringArray>
[ nan, '20', '37',  '4',  '9', '10',  '7',  '1', '15', '30', '31',  '6', '12',
 '22',  '5', '36', '25', '44', '24', '18',  '3',  '8', '50', '11', '29', '40',
 '39',  '2', '42', '34', '19', '35', '16', '33', '13', '23', '14', '28', '17',
 '21', '43', '46', '26', '32', '41', '45', '27', '38', '48', '47',  '0', '49']
Length: 52, dtype: str

In [97]:
df['YearsCode'].astype('float').mean()

np.float64(14.193255274014932)