In [1]:
import pandas as pd

data = {
    "first": ["Ramesh","Rajesh","Mahesh"],
    "last" : ["Govardhan","singh","pablo"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [13]:
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [12]:
df.apply(len)

first    3
last     3
age      3
email    3
dtype: int64

In [18]:
x = 20 if True  else 20

In [21]:
df.map(lambda x:  len(str(x)) if isinstance(x, (int,float))  else len(x))

   first  last  age  email
0      6     9    2     15
1      6     5    2     15
2      6     5    2     15

In [23]:
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [ ]:
df['first'].map({"Rajesh":"Kajoo"}) #rest become non, so we should use replace to avoid that

0      NaN
1    Kajoo
2      NaN
Name: first, dtype: str

In [27]:
df['first'] = df['first'].replace({"Ramesh":"Kajoo"})

In [28]:
df

    first       last  age            email
0   Kajoo  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [37]:
df['isAge'] = df['age'].apply(lambda x: True if x>30 else False)


df

    first       last  age            email  isAge
0   Kajoo  Govardhan   23  ramesh@mail.com  False
1  Rajesh      singh   34  rajesh@mail.com   True
2  Mahesh      pablo   25  mahesh@mail.com  False