

### Data Cleaning
   Data cleaning means fixing bad data in your data set.

Bad data could be:

- Empty cells
- Data in wrong format
- Wrong data
- Duplicates

In [2]:
import pandas as pd

In [3]:

df = pd.read_csv("bad_data.csv")

In [14]:
df

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist

In [13]:
# drop nan and invalid row
df.dropna()

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist

In [ ]:
df = pd.read_csv('bad_data.csv')

df.dropna(inplace = True) # will not return new df, it's just replace the existing one

In [17]:
df

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist

In [20]:
df = pd.read_csv('bad_data.csv')

df.info()

df

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          5 non-null      int64
 1   First Name     5 non-null      str
 2   Last Name      5 non-null      str
 3   Sex            5 non-null      str
 4   Email          4 non-null      str
 5   Phone          5 non-null      str
 6   Date of birth  4 non-null      str
 7   Job Title      5 non-null      str
dtypes: int64(1), str(7)
memory usage: 452.0 bytes

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,NaN,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,NaN,Planning and development surveyor

In [23]:
df.fillna("uknown", inplace = True)

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,uknown,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,uknown,Planning and development surveyor

In [24]:
df = pd.read_csv('bad_data.csv')
df

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,NaN,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,NaN,Planning and development surveyor

In [27]:
cleaned_df = df.fillna({"Email":"d@support.co.in"},inplace=False)

cleaned_df

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,d@support.co.in,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,NaN,Planning and development surveyor

In [28]:
cleaned_df

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,d@support.co.in,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,NaN,Planning and development surveyor

In [ ]:
df = pd.read_json("employee_data.json")

df.head()

,position,text,answers
0,1,Usually you:,"[{'position': 1, 'text': 'communicative'}, {'p..."
1,2,You more often allow:,"[{'position': 1, 'text': 'feelings control you..."
2,3,"When you decide to go somewhere for one day, y...","[{'position': 1, 'text': 'plan what and when y..."
3,4,Being in a company you usually:,"[{'position': 1, 'text': 'join the conversatio..."
4,5,You can most likely be called:,"[{'position': 1, 'text': 'practical person'}, ..."

In [38]:
df['position'].mean()

np.float64(37.5)

In [39]:
df['position'].median()

np.float64(37.5)

In [42]:
df['position'].mean()

np.float64(37.5)

In [66]:
wrong_data = {
    "name": ["Ramesh","Rajoo","Kalpesh","Somesh","Randheer"],
    "age": [22, 34, 78, 89, 34],
    "salary": [ 2000, 1500, None,1600, 1300],
    "doj": ["2026-05-21", "20260620", "2022-05-30", None, "20221204"],
    "email": [ "ramesh@mail.com", "rajoo@mail.com", "kalpesh@mail", None,"randheer@mail.com"]
}


df = pd.DataFrame(wrong_data)

In [67]:
df

       name  age  salary         doj              email
0    Ramesh   22  2000.0  2026-05-21    ramesh@mail.com
1     Rajoo   34  1500.0    20260620     rajoo@mail.com
2   Kalpesh   78     NaN  2022-05-30       kalpesh@mail
3    Somesh   89  1600.0         NaN                NaN
4  Randheer   34  1300.0    20221204  randheer@mail.com

In [53]:
"""Let's try to convert all cells in the 'Date' column into dates.

Pandas has a to_datetime() method for this:"""

"Let's try to convert all cells in the 'Date' column into dates.\n\nPandas has a to_datetime() method for this:"

In [ ]:
pd.to_datetime(df['doj'], format="mixed") #NaT ==> not a time

0   2026-05-21
1   2026-06-20
2   2022-05-30
3          NaT
4   2022-12-04
Name: doj, dtype: datetime64[us]

In [72]:
df.dropna(subset=['doj','salary'], inplace = True)

In [73]:
df

       name  age  salary         doj              email
0    Ramesh   22  2000.0  2026-05-21    ramesh@mail.com
1     Rajoo   34  1500.0    20260620     rajoo@mail.com
4  Randheer   34  1300.0    20221204  randheer@mail.com

# set duration and replace

In [77]:
df.loc[1,'age']=40

In [78]:
df

       name  age  salary         doj              email
0    Ramesh   22  2000.0  2026-05-21    ramesh@mail.com
1     Rajoo   40  1500.0    20260620     rajoo@mail.com
4  Randheer   34  1300.0    20221204  randheer@mail.com

In [ ]:
df.loc['age']

0    22
1    40
4    34
Name: age, dtype: int64

In [86]:
for idx in df.index:
    print(idx)
    print(df.loc[idx])
    print()

0
name               Ramesh
age                    22
salary             2000.0
doj            2026-05-21
email     ramesh@mail.com
Name: 0, dtype: object

1
name               Rajoo
age                   40
salary            1500.0
doj             20260620
email     rajoo@mail.com
Name: 1, dtype: object

4
name               Randheer
age                      34
salary               1300.0
doj                20221204
email     randheer@mail.com
Name: 4, dtype: object

In [90]:
#removing the row


df.drop(1, inplace=True)
df

       name  age  salary       doj              email
4  Randheer   34  1300.0  20221204  randheer@mail.com

In [92]:
# Removing Duplicates

wrong_data = {
    "name": ["Ramesh","Rajoo","Kalpesh","Somesh","Ramesh"],
    "age": [22, 34, 78, 89, 22],
    "salary": [ 2000, 1500, None,1600, 2000],
    "doj": ["2026-05-21", "20260620", "2022-05-30", None, "2026-05-21"],
    "email": [ "ramesh@mail.com", "rajoo@mail.com", "kalpesh@mail", None,"ramesh@mail.com"]
}


df = pd.DataFrame(wrong_data)

In [93]:
df

      name  age  salary         doj            email
0   Ramesh   22  2000.0  2026-05-21  ramesh@mail.com
1    Rajoo   34  1500.0    20260620   rajoo@mail.com
2  Kalpesh   78     NaN  2022-05-30     kalpesh@mail
3   Somesh   89  1600.0         NaN              NaN
4   Ramesh   22  2000.0  2026-05-21  ramesh@mail.com

In [95]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [96]:
df

      name  age  salary         doj            email
0   Ramesh   22  2000.0  2026-05-21  ramesh@mail.com
1    Rajoo   34  1500.0    20260620   rajoo@mail.com
2  Kalpesh   78     NaN  2022-05-30     kalpesh@mail
3   Somesh   89  1600.0         NaN              NaN
4   Ramesh   22  2000.0  2026-05-21  ramesh@mail.com

In [97]:
df.drop_duplicates(inplace = True)
df

      name  age  salary         doj            email
0   Ramesh   22  2000.0  2026-05-21  ramesh@mail.com
1    Rajoo   34  1500.0    20260620   rajoo@mail.com
2  Kalpesh   78     NaN  2022-05-30     kalpesh@mail
3   Somesh   89  1600.0         NaN              NaN