In [20]:
import pandas 
import pandas as pd 
import pathlib

In [67]:
BASE_DIR = pathlib.Path("../").resolve().parent

RESOURCE_DIR = BASE_DIR / "resources"


data_csv = RESOURCE_DIR / "data" / "data.csv"

bad_data_csv = RESOURCE_DIR / "data" / "bad_data.csv"


employee_data_json = RESOURCE_DIR / "data" / "employee_data.json"

In [22]:

df = pd.read_csv(data_csv)

df.head()

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,tsharp@example.net,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,17-11-89,Planning and development surveyor

In [23]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [24]:
pd.__version__

'3.0.3'

In [25]:
a = [1, 7, 2]

myvar = pd.Series(a)

myvar

0    1
1    7
2    2
dtype: int64

In [26]:
myvar[0]

np.int64(1)

In [27]:
a = [1,2,3]

myvar = pd.Series(a, index = ['x','y','z'])

myvar

x    1
y    2
z    3
dtype: int64

In [28]:
myvar['x']

np.int64(1)

In [29]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)

In [30]:
myvar

day1    420
day2    380
day3    390
dtype: int64

In [31]:
# only use data from day1 and day2

myvar = pd.Series(calories, index = ["day1", "day2"])

myvar

day1    420
day2    380
dtype: int64

In [32]:
vars = pd.Series([1,2,3], index = ['x','y','z'])

vars

x    1
y    2
z    3
dtype: int64

In [33]:
vars['x']

np.int64(1)

In [49]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [50]:
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [51]:
df.loc[0] #return panda Series

calories    420
duration     50
Name: 0, dtype: int64

In [52]:
df.loc[[0, 1]] #return panda dataframe

   calories  duration
0       420        50
1       380        40

In [53]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

In [54]:
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [55]:
df.loc['day2']

calories    380
duration     40
Name: day2, dtype: int64

In [56]:
df.loc[['day2','day1']]

      calories  duration
day2       380        40
day1       420        50

In [58]:
pd.options.display.max_rows

10

In [59]:
pd.options.display.max_rows = 10

In [61]:
df = pd.read_csv(data_csv)

In [62]:
df

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,tsharp@example.net,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,17-11-89,Planning and development surveyor
...,...,...,...,...,...,...,...,...
9995,9996,Tina,Sherman,Male,bartlettcolleen@example.org,(455)476-4044x5755,28-07-74,"Scientist, physiological"
9996,9997,Earl,Jennings,Female,andreabenton@example.com,009.056.6505,20-08-32,Warehouse manager
9997,9998,Ellen,Dominguez,Female,michaelayoder@example.net,409-428-4297x469,06-06-66,Lawyer
9998,9999,Emma,Clark,Male,pstrickland@example.com,849-868-8653,09-05-07,Accounting technician
9999,10000,Katrina,Schwartz,Female,andres56@example.org,001-874-330-5546x16770,14-08-35,Drilling engineer

In [63]:
display(df)

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,tsharp@example.net,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,17-11-89,Planning and development surveyor
...,...,...,...,...,...,...,...,...
9995,9996,Tina,Sherman,Male,bartlettcolleen@example.org,(455)476-4044x5755,28-07-74,"Scientist, physiological"
9996,9997,Earl,Jennings,Female,andreabenton@example.com,009.056.6505,20-08-32,Warehouse manager
9997,9998,Ellen,Dominguez,Female,michaelayoder@example.net,409-428-4297x469,06-06-66,Lawyer
9998,9999,Emma,Clark,Male,pstrickland@example.com,849-868-8653,09-05-07,Accounting technician
9999,10000,Katrina,Schwartz,Female,andres56@example.org,001-874-330-5546x16770,14-08-35,Drilling engineer

In [69]:
employee_data_json

PosixPath('/home/suanki/Desktop/overflowwithpyspark/resources/data/employee_data.json')

In [68]:
df_json = pd.read_json(employee_data_json)

In [ ]:
df_json

,position,text,answers
0,1,Usually you:,"[{'position': 1, 'text': 'communicative'}, {'p..."
1,2,You more often allow:,"[{'position': 1, 'text': 'feelings control you..."
2,3,"When you decide to go somewhere for one day, y...","[{'position': 1, 'text': 'plan what and when y..."
3,4,Being in a company you usually:,"[{'position': 1, 'text': 'join the conversatio..."
4,5,You can most likely be called:,"[{'position': 1, 'text': 'practical person'}, ..."
...,...,...,...
69,70,Your age.,"[{'position': 1, 'text': 'up to 20 years old'}..."
70,71,Your gender.,"[{'position': 1, 'text': 'Male'}, {'position':..."
71,72,Marital Status.,"[{'position': 1, 'text': 'Not married'}, {'pos..."
72,73,I am dependent.,"[{'position': 1, 'text': 'Ð¶ÐµÐ½Ð° (Ð¼ÑƒÐ¶)'},..."
73,74,Financial Obligations.,"[{'position': 1, 'text': 'Mortgage'}, {'positi..."

In [80]:
pd.set_option("display.max_colwidth",100)

In [81]:
display(df_json)

,position,text,answers
0,1,Usually you:,"[{'position': 1, 'text': 'communicative'}, {'position': 2, 'text': 'quite restrained and calm'}]"
1,2,You more often allow:,"[{'position': 1, 'text': 'feelings control your mind'}, {'position': 2, 'text': 'the mind to con..."
2,3,"When you decide to go somewhere for one day, you usually:","[{'position': 1, 'text': 'plan what and when you will do'}, {'position': 2, 'text': 'just hit th..."
3,4,Being in a company you usually:,"[{'position': 1, 'text': 'join the conversation'}, {'position': 2, 'text': 'talk with each separ..."
4,5,You can most likely be called:,"[{'position': 1, 'text': 'practical person'}, {'position': 2, 'text': 'fictional, romantic'}]"
...,...,...,...
69,70,Your age.,"[{'position': 1, 'text': 'up to 20 years old'}, {'position': 2, 'text': '20-24 years old'}, {'po..."
70,71,Your gender.,"[{'position': 1, 'text': 'Male'}, {'position': 2, 'text': 'Female'}]"
71,72,Marital Status.,"[{'position': 1, 'text': 'Not married'}, {'position': 2, 'text': 'Married'}]"
72,73,I am dependent.,"[{'position': 1, 'text': 'Ð¶ÐµÐ½Ð° (Ð¼ÑƒÐ¶)'}, {'position': 2, 'text': '1 child'}, {'position': ..."
73,74,Financial Obligations.,"[{'position': 1, 'text': 'Mortgage'}, {'position': 2, 'text': 'Car Loan'}, {'position': 3, 'text..."

In [ ]:

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

In [ ]:
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [ ]:
df = pd.read_csv("data.csv")

In [ ]:
df.head()

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,tsharp@example.net,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,17-11-89,Planning and development surveyor

In [ ]:
df.tail()

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
9995,9996,Tina,Sherman,Male,bartlettcolleen@example.org,(455)476-4044x5755,28-07-74,"Scientist, physiological"
9996,9997,Earl,Jennings,Female,andreabenton@example.com,009.056.6505,20-08-32,Warehouse manager
9997,9998,Ellen,Dominguez,Female,michaelayoder@example.net,409-428-4297x469,06-06-66,Lawyer
9998,9999,Emma,Clark,Male,pstrickland@example.com,849-868-8653,09-05-07,Accounting technician
9999,10000,Katrina,Schwartz,Female,andres56@example.org,001-874-330-5546x16770,14-08-35,Drilling engineer

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          10000 non-null  int64
 1   First Name     10000 non-null  str
 2   Last Name      10000 non-null  str
 3   Sex            10000 non-null  str
 4   Email          10000 non-null  str
 5   Phone          10000 non-null  str
 6   Date of birth  10000 non-null  str
 7   Job Title      10000 non-null  str
dtypes: int64(1), str(7)
memory usage: 625.1 KB

In [83]:
df.shape

(10000, 8)