In [1]:



import pandas as pd

In [18]:
data = {
    "name": ["Ramesh","Rajesh","Mahesh"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)

In [19]:
df = pd.DataFrame(data)

In [20]:
df

     name  age            email
0  Ramesh   23  ramesh@mail.com
1  Rajesh   34  rajesh@mail.com
2  Mahesh   25  mahesh@mail.com

In [21]:
df["name"]

0    Ramesh
1    Rajesh
2    Mahesh
Name: name, dtype: str

In [22]:
df.email

0    ramesh@mail.com
1    rajesh@mail.com
2    mahesh@mail.com
Name: email, dtype: str

In [26]:
df.count()

name     3
age      3
email    3
dtype: int64

In [27]:
type(df["name"])

pandas.Series

In [28]:
s = pd.Series([1.2,3.6,3.7,8.9])

In [8]:
s

0    1.2
1    3.6
2    3.7
3    8.9
dtype: float64

In [29]:
df[["name","email"]]

     name            email
0  Ramesh  ramesh@mail.com
1  Rajesh  rajesh@mail.com
2  Mahesh  mahesh@mail.com

In [30]:
df.columns

Index(['name', 'age', 'email'], dtype='str')

In [31]:
df.iloc[0]

name              Ramesh
age                   23
email    ramesh@mail.com
Name: 0, dtype: object

In [32]:
type(df.iloc[0])

pandas.Series

In [33]:
df.iloc[[0,1]]

     name  age            email
0  Ramesh   23  ramesh@mail.com
1  Rajesh   34  rajesh@mail.com

In [34]:
df.iloc[[0,1],[0,2]] #first list is row and # second list is for column

     name            email
0  Ramesh  ramesh@mail.com
1  Rajesh  rajesh@mail.com

In [35]:
df

     name  age            email
0  Ramesh   23  ramesh@mail.com
1  Rajesh   34  rajesh@mail.com
2  Mahesh   25  mahesh@mail.com

In [36]:
df.loc[0]

name              Ramesh
age                   23
email    ramesh@mail.com
Name: 0, dtype: object

In [37]:
df.loc[[0,1]]

     name  age            email
0  Ramesh   23  ramesh@mail.com
1  Rajesh   34  rajesh@mail.com

In [38]:
df.loc[[0,1],['email']]

             email
0  ramesh@mail.com
1  rajesh@mail.com

In [39]:
df

     name  age            email
0  Ramesh   23  ramesh@mail.com
1  Rajesh   34  rajesh@mail.com
2  Mahesh   25  mahesh@mail.com

In [40]:
updated_df =df.set_index('name') # inplace=True

In [41]:
df

     name  age            email
0  Ramesh   23  ramesh@mail.com
1  Rajesh   34  rajesh@mail.com
2  Mahesh   25  mahesh@mail.com

In [42]:
updated_df

        age            email
name
Ramesh   23  ramesh@mail.com
Rajesh   34  rajesh@mail.com
Mahesh   25  mahesh@mail.com

In [43]:
updated_df.loc['Ramesh','email']

'ramesh@mail.com'

In [44]:
updated_df['email']

name
Ramesh    ramesh@mail.com
Rajesh    rajesh@mail.com
Mahesh    mahesh@mail.com
Name: email, dtype: str

In [45]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [46]:
updated_df.index

Index(['Ramesh', 'Rajesh', 'Mahesh'], dtype='str', name='name')

In [47]:
df.set_index('email', inplace=True)

In [48]:
df

                   name  age
email
ramesh@mail.com  Ramesh   23
rajesh@mail.com  Rajesh   34
mahesh@mail.com  Mahesh   25

In [49]:
df.reset_index()

             email    name  age
0  ramesh@mail.com  Ramesh   23
1  rajesh@mail.com  Rajesh   34
2  mahesh@mail.com  Mahesh   25

In [50]:
df

                   name  age
email
ramesh@mail.com  Ramesh   23
rajesh@mail.com  Rajesh   34
mahesh@mail.com  Mahesh   25

## filtering Data

In [51]:
import pandas as pd

data = {
    "first": ["Ramesh","Rajesh","Mahesh"],
    "last" : ["Govardhan","singh","pablo"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)

In [52]:
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [53]:
# want where last name is singh

df['last'] == "singh"

0    False
1     True
2    False
Name: last, dtype: bool

In [9]:
name_filter = df['last'] == "singh"

df[name_filter]

    first   last  age            email
1  Rajesh  singh   34  rajesh@mail.com

In [54]:
df.loc[name_filter]

    first   last  age            email
1  Rajesh  singh   34  rajesh@mail.com

In [55]:
df.loc[name_filter,'email']

1    rajesh@mail.com
Name: email, dtype: str

In [59]:
last_name_filter = (df['last'] == 'singh') & (df['first'] == 'Rajesh')
df.loc[last_name_filter]

    first   last  age            email
1  Rajesh  singh   34  rajesh@mail.com

In [60]:
last_name_filter = (df['last'] == 'singh') | (df['first'] == 'Rajesh')
df.loc[last_name_filter]

    first   last  age            email
1  Rajesh  singh   34  rajesh@mail.com

In [62]:
df.loc[~last_name_filter]   #opposit of filter

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

### Changing column names

In [175]:
import pandas as pd

data = {
    "first": ["Ramesh","Rajesh","Mahesh"],
    "last" : ["Govardhan","singh","pablo"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)

In [67]:
df.columns = ['first_name', 'last_name', "age", "email"]

In [65]:
df

  first_name  last_name  age            email
0     Ramesh  Govardhan   23  ramesh@mail.com
1     Rajesh      singh   34  rajesh@mail.com
2     Mahesh      pablo   25  mahesh@mail.com

In [177]:
df.columns = [i.upper() for i in list(df.columns)]

In [74]:
df

  FIRST_NAME  LAST_NAME  AGE            EMAIL
0     Ramesh  Govardhan   23  ramesh@mail.com
1     Rajesh      singh   34  rajesh@mail.com
2     Mahesh      pablo   25  mahesh@mail.com

In [77]:
df.columns = df.columns.str.replace('_','')

In [78]:
df

  FIRSTNAME   LASTNAME  AGE            EMAIL
0    Ramesh  Govardhan   23  ramesh@mail.com
1    Rajesh      singh   34  rajesh@mail.com
2    Mahesh      pablo   25  mahesh@mail.com

In [81]:
df.FIRSTNAME

0    Ramesh
1    Rajesh
2    Mahesh
Name: FIRSTNAME, dtype: str

In [180]:
df.rename(columns={"FIRSTNAME":"first","LASTNAME":"last"}, inplace=True)

In [84]:
df

    first       last  AGE            EMAIL
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

## renaming column value

In [85]:
df

    first       last  AGE            EMAIL
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [86]:
df.loc[2]

first             Mahesh
last               pablo
AGE                   25
EMAIL    mahesh@mail.com
Name: 2, dtype: object

In [128]:
df.loc[2] = ['John','Doe',25,'john@mail.com']  #change existing
df.loc[3] = ['Ramsh','Govardhan',25,'Govardhan@mail.com']  #add new row
df.loc[6] = ['Rajoo','Kejaria',25,'rajoo@mail.com']  #add new row with different index

In [112]:
df

    first       last  age               email
0  Ramesh  Govardhan   23     ramesh@mail.com
1  Rajesh      singh   34     rajesh@mail.com
2    John        Doe   25       john@mail.com
3   Ramsh  Govardhan   25  Govardhan@mail.com
6   Rajoo    Kejaria   25      rajoo@mail.com

In [115]:
df.loc[6,'email'] = 'kajoo@mail.com'

In [116]:
df

    first       last  age               email           EMAIL
0  Ramesh  Govardhan   23     ramesh@mail.com             NaN
1  Rajesh      singh   34     rajesh@mail.com             NaN
2    John        Doe   25       john@mail.com             NaN
3   Ramsh  Govardhan   25  Govardhan@mail.com             NaN
6   Rajoo    Kejaria   25      kajoo@mail.com  kajoo@mail.com

In [129]:
filter_and_replace_condition = df['age'] == 25

df[filter_and_replace_condition]

   first       last  age               email
2   John        Doe   25       john@mail.com
3  Ramsh  Govardhan   25  Govardhan@mail.com
6  Rajoo    Kejaria   25      rajoo@mail.com

In [131]:
df.loc[filter_and_replace_condition,'age'] = 100

In [133]:
df

    first       last  age               email
0  Ramesh  Govardhan   23     ramesh@mail.com
1  Rajesh      singh   34     rajesh@mail.com
2    John        Doe  100       john@mail.com
3   Ramsh  Govardhan  100  Govardhan@mail.com
6   Rajoo    Kejaria  100      rajoo@mail.com

In [160]:
import pandas as pd

data = {
    "first": ["Ramesh","Rajesh","Mahesh"],
    "last" : ["Govardhan","singh","pablo"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [134]:
# Make all email address to upper case

In [161]:
df['email'] = df['email'].str.upper() #assgin the value

In [162]:
df

    first       last  age            email
0  Ramesh  Govardhan   23  RAMESH@MAIL.COM
1  Rajesh      singh   34  RAJESH@MAIL.COM
2  Mahesh      pablo   25  MAHESH@MAIL.COM

## other method which do the same

appy
map
applymap

In [144]:
df['email'].apply(len) # apply len on each  value

0    15
1    15
2    13
3    18
6    14
Name: email, dtype: int64

In [148]:
df

    first       last  age               email
0  Ramesh  Govardhan   23     RAMESH@MAIL.COM
1  Rajesh      singh   34     RAJESH@MAIL.COM
2    John        Doe  100       JOHN@MAIL.COM
3   Ramsh  Govardhan  100  GOVARDHAN@MAIL.COM
6   Rajoo    Kejaria  100      RAJOO@MAIL.COM

In [163]:
def update_email(email):
    return email.lower()

In [164]:
df['email']=df['email'].apply(update_email)

In [165]:
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [166]:
df['email'].apply(lambda x: x.upper())

0    RAMESH@MAIL.COM
1    RAJESH@MAIL.COM
2    MAHESH@MAIL.COM
Name: email, dtype: str

In [167]:
# apply len function on each series(column)

df.apply(len)

first    3
last     3
age      3
email    3
dtype: int64

In [168]:
df.apply(len, axis='columns')

0    4
1    4
2    4
dtype: int64

In [169]:
len(df['email'])

3

In [170]:
df.apply(pd.Series.min)

first             Mahesh
last           Govardhan
age                   23
email    mahesh@mail.com
dtype: object

In [172]:
df.apply(lambda x: x.min())

first             Mahesh
last           Govardhan
age                   23
email    mahesh@mail.com
dtype: object